FROM fluent/fluentd:v1.12.0-debian-1.0

USER root

COPY ./config/fluent.conf /fluentd/etc
# COPY ./script/log_generator.sh /script/log_generator.sh

# RUN sh /script/log_generator.sh > /dev/null 2>&1 &
